version: '3'

services:
  mongo:
    image: mongo:3.4.19-jessie
    container_name: ca-mongo
    volumes:
      - ./db:/data/db
  idxMongo:
    image: mongo:3.4.19-jessie
    container_name: ca-idx
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
  bindaas:
    build: "./Deps/Bindaas/"
    depends_on:
      - "mongo"
    ports:
      - "8080:8080"
      - "9099:9099"
    container_name: ca-data
    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json
  iip:
    build: "https://github.com/camicroscope/iipImage.git#v3.2.0"
    container_name: ca-iip
    volumes:
      - ./images/:/images/
  viewer:
    build: "https://github.com/camicroscope/caMicroscope.git#develop"
    container_name: ca-front
    volumes:
      - ./config/login.html:/var/www/html/login.html
  loader:
    build: "https://github.com/camicroscope/SlideLoader.git#v3.2.0"
    container_name: ca-load
    volumes:
      - ./images/:/images/
  security:
    build: "https://github.com/camicroscope/Security.git#v3.2.1"
    container_name: ca-security
    ports:
      - "4010:4010"
    volumes:
      - ./config/routes.json:/root/src/routes.json
      - ./jwt_keys/:/keys/
    environment:
      - DISABLE_SEC=true
  auth:
    build: "./Deps/auth_service/"
    volumes:
      - ./jwt_keys/:/keys/
    container_name: ca-auth
